language: ruby
os: 
  - linux
arch: amd64
branches:
  only:
  - master
services:
  - docker
before_install:
  - date --help
  - export VERSION=$TRAVIS_COMMIT.$TRAVIS_BUILD_ID
  - export BUILD_DATE=$(date ""+%b %d %Y@%H:%M:%S %Z"")
  - docker build -t $DOCKER_REPO .
script:
  - docker images $DOCKER_REPO
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
