#!/usr/bin/with-contenv bash

PUID=${PUID:-1111}
PGID=${PGID:-1111}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
%++++++++++++++++++++++++++++++++++++++++++++++++++++++%
 888888 8888888              88 8888888                    
   88   88                   88 88    db                    
   88   88                   88 88                           
   88   88888 .d8b.   .d8b.  88 88888 88 8888b.  .d8b.  
   88   88   d8P Y8b d8P Y8b 88 88    88 88  8b d8P Y8b 
   88   88   8888888 8888888 88 88    88 88  88 8888888 
   88   88   Y8b.    Y8b.    88 88    88 88  88 Y8b.    
 888888 88    ºY888P  ºY888P 88 88    88 88  88  ºY888P 
                                  (c) I Feel Fine, Inc.
%++++++++++++++++++++++++++++++++++++++++++++++++++++++%
 Based on the great work done by linuxserver.io. 
 They accept donations at https://linuxserver.io/donate

%------------------------------------------------------%
 GUID/UID:
 User uid:    $(id -u abc)
 User gid:    $(id -g abc)
%------------------------------------------------------%
"
chown -R abc:abc /config